### ISSUE TITLE
Found POST: r-api.iaqualink.net/devices/XXXX/control.json?   

### ISSUE THREAD

**Issue by haydonryan** [tekkamanendless/iaqualink#10]
Hi There, 
Love that you've started this. I submitted a feature request to iaqualink years ago for a push notification on completion, but it never made it into the product.   I've been thinking about a possible homeassistant plugin to notify me when my pool cleaner has finished by polling the status.  

When I setup mitm I found that it's calling a `control.json` not the `execute_read_command.json` listed in your docs and wanted to let you know.

Thanks!

```
https://r-api.iaqualink.net/devices/${Device}/control.json?\
user_id=${userid}&command=/command&api_key=XXX&params=request=0A11&\
timeout=800&authentication_token=XXXX&sessionID=XXXX HTTP/2.0 

Response body:
JSON
{
    "command": {
        "request": "0A11",
        "response": "001101000AA0789300221C001F4309000000"
    },
    "requestID": ""
}



```

**Comment by tekkamanendless** [comment]
Could give me the model number of your robot?

Also, try the `execute_read_command.json` endpoint and see if it works.  Maybe `control.json` is an alias for `execute_read_command.json` or _vice versa_.  My robot won't be back online until April.

**Comment by haydonryan** [comment]
I have the Polaris 9659iQ, just tried - yes you're right it's an alias.

**Comment by haydonryan** [comment]
I'm also struggling to get the shadow call to work with my device.  Does the zodiac api only work with zodiac products?  And I don't understand that it's identical to the v1 get - I don't see that documented... are you able to shed light on this please?

```
GET /devices/v2/${device}/shadow

This seems to be identical to GET /devices/v1/${device}/shadow.```

**Comment by tekkamanendless** [comment]
Different subsets of devices support different APIs.  Some of the newer stuff that uses web sockets seem to support more endpoints.  My little robot only supports the original few API endpoints that were committed.

**Comment by haydonryan** [comment]
Awesome :) keep up the great work. Closing this.
