### ISSUE TITLE
{"status":"500","error":{"error_code":"error_internal_server_error","message":"Device offline.","details":"An internal server error has occurred."}}%

### ISSUE THREAD

**Issue by johntdyer** [tekkamanendless/iaqualink#6]
Hello,

   Thanks for doing the heavy lifting on this one, its super cool and I am super excited to get this working !!! So I used [http2curl]("github.com/moul/http2curl") to get the curl you're using in an effort to further debug my problem...  TLDR this query fails 
```

> curl -X 'POST' -H 'Accept: application/json' 'https://p-api.iaqualink.net/devices/34XXX/execute_read_command.json?api_key=XXXXXXXXX&authentication_token=XXXXXXXXXX&command=%2Fcommand&params=request%3D0A1240%26timeout%3D800&user_id=444XXX
{"status":"500","error":{"error_code":"error_internal_server_error","message":"Device offline.","details":"An internal server error has occurred."}}%
```

but the device is definitely online

![image](https://user-images.githubusercontent.com/58234/192027571-1a8caf96-4599-43f6-84a0-fbc83abdb701.png)

Any thoughts as to what might be going on ?

**Comment by tekkamanendless** [comment]
Can you send me the model of your robot?  It looks like iAquaLink supports
a variety of different protocols, and I'm currently working with someone
whose robot uses a Web Sockets API instead of the REST API that mine does.
Yours might fall under that category for when we get support for that
included.

**Comment by johntdyer** [comment]
Figured out that the ID is not the "device_id" the the response from ./iaqualink devices but is actually the serial number... figured this out w/ MITMProxy on my phone :)

**Comment by johntdyer** [comment]
Thanks again for making this project, super cool !   If I can help w/ testing or anything please let me know :)
